const Map<String, Map<String, String>> i18n = {
  'KR': {
    'title': 'BOSCO TERMINAL',
    'live': 'Live',
    'highlights': 'DoubleXP',
    'deep_dives': 'Deep Dive',
    'settings': '설정',
    'lang_select': '시스템 언어 선택',
    'season_select': '활성 시즌 선택',
    'season_note': '데이터 소스에서 제공하는 모든 시즌 정보를 제공합니다.',
    'standard': '표준 (Standard)',
    'show_warnings': '미션 주의사항 표시',
    'donation': '개발자 후원',
    'donate_note': '후원금은 Apple Store 등록비 및 서버 유지비로 사용됩니다.',
    'disclaimer_title': '면책 조항 및 권리 고지',
    'disclaimer_body': '본 앱은 Ghost Ship Games와 관련이 없는 비공식 팬 프로젝트입니다. DRG의 모든 자산 및 상표권은 원작자에게 있습니다. 실시간 데이터는 doublexp.net에서 제공되며, 게임 내 미션 생성 로직을 분석하여 정제된 데이터를 공유해주신 rolfosian(GitHub)님께 특별한 감사를 표합니다.',
    'current': '현재 진행 중',
    'upcoming': '다음 미션',
    'past': '종료된 미션',
    'length': '길이',
    'complexity': '복잡도',
    'time_left': '다음 로테이션:',
    'timeline_title': '오늘의 주요 미션 타임라인',
    'now': '--- [ 현재 시간 ] ---',
    'details': '미션 상세 정보',
    'close': '닫기',
    'no_highlights': '오늘의 특별한 미션이 없습니다.',
    'steam_profile': 'Developer & Community',
    'visit_steam': 'Pinyo의 프로필 방문',
    'bug_report': '버그 제보 및 수정 문의',
    'bug_report_note': '미션 데이터 오류나 앱 버그는 스팀 메시지로 알려주세요.',
    'copy_link': '링크 복사',
    'link_copied': '클립보드에 복사되었습니다!',
    'long_press_copy': '길게 누르면 링크 복사',
    'tomorrow': '내일 일정',
    
    'standard_dd': '일반 딥 다이브',
    'elite_dd': '엘리트 딥 다이브',

    // Map Name
    'Azure Weald': '바닷빛 삼림',
    'Crystalline Caverns': '크리스탈라인 동굴',
    'Dense Biozone': '고밀도 생태지역',
    'Fungus Bogs': '곰팡이 늪지',
    'Glacial Strata': '빙하 지층',
    'Hollow Bough': '빈 줄기',
    'Magma Core': '마그마 코어',
    'Radioactive Exclusion Zone': '방사능 위험 구역',
    'Salt Pits': '소금 구덩이',
    'Sandblasted Corridors': '사막화 지대',
    'Ossuary Depths': '뼈동굴 심층부',

    // Mission Type
    'Mining Expedition': '채굴 원정',
    'Egg Hunt': '알 추적',
    'On-Site Refining': '현장 정제',
    'Point Extraction': '채굴 지점',
    'Salvage Operation': '구조 임무',
    'Escort Duty': '호위 임무',
    'Elimination': '섬멸',
    'Industrial Sabotage': '기업 방해공작',
    'Deep Scan': '심층 탐사',
    'Heavy Excavation': '대형 발굴',
    
    // Mutators & Warnings
    'Double XP': '경험치 2배',
    'Gold Rush': '황금 광풍',
    'Mineral Mania': '광물 마니아',
    'Low Gravity': '저중력',
    'Rich Atmosphere': '풍부한 산소',
    'Critical Weakness': '치명적 약점',
    'Golden Bugs': '황금 벌레',
    'Volatile Guts': '불안정한 내장',
    'Shield Disruption': '보호막 분쇄',
    'Mactera Plague': '막테라 역병',
    'Cave Leech Cluster': '케이브 리치 군집',
    'Parasites': '기생충',
    'Exploder Infestation': '익스플로더 감염',
    'Lethal Enemies': '치명적인 적',
    'Low Oxygen': '산소 부족',
    'Haunted Cave': '유령 동굴',
    'Elite Threat': '엘리트 위협',
    'Swarmageddon': '스웜아게돈',
    'Rival Presence': '라이벌 출현',
    'Lithophage Outbreak': '리쏘페이지 발생',
    'Regenerative Bugs': '재생형 벌레',
    'Pit Jaw Colony': '갱구 악어 군락',
    'Duck and Cover': '엄폐!',
    'Ebonite Outbreak': '에보나이트 발생',
    'Scrab Nesting Grounds': '스크랩 둥지',
    'signal_lost': '통신 두절!',
    'signal_lost_desc': '보스코가 신호를 잃었습니다! 데이터가 너무 오래되었습니다.',
    'offline_mode': '오프라인 모드',
    'offline_mode_desc': 'Hoxxes 전파 상태가 좋지 않습니다. 캐시된 데이터를 사용 중입니다.',
    'dd_loading': '딥 다이브 데이터를 불러오는 중...',
    'dd_error': '딥 다이브 데이터를 불러올 수 없습니다.',
    'dd_next_update': '다음 갱신:',
    'no_warnings': '주의사항 없음',
  },
  'EN': {
    'title': 'BOSCO TERMINAL',
    'live': 'LIVE',
    'highlights': 'HIGHLIGHTS',
    'deep_dives': 'DEEP DIVES',
    'settings': 'SETTINGS',
    'lang_select': 'System Language',
    'season_select': 'Active Season',
    'season_note': 'Providing all season data from the source.',
    'standard': 'Standard',
    'show_warnings': 'Show Mission Warnings',
    'donation': 'Support Developer',
    'donate_note': 'Used for Store fees and maintenance.',
    'disclaimer_title': 'Legal Disclaimer',
    'disclaimer_body': 'This app is an unofficial fan project and is not affiliated with Ghost Ship Games. All game assets and trademarks belong to their respective owners. Real-time data is sourced from doublexp.net. Special thanks to rolfosian (GitHub) for analyzing the in-game mission generation logic and providing this reconstructed data source.',
    'current': 'CURRENT',
    'upcoming': 'UPCOMING',
    'past': 'PAST',
    'length': 'Length',
    'complexity': 'Complexity',
    'time_left': 'Next Rotation:',
    'timeline_title': 'Today\'s Highlight Timeline',
    'now': '--- [ CURRENT TIME ] ---',
    'details': 'Mission Details',
    'close': 'CLOSE',
    'no_highlights': 'No special missions found for today.',
    'steam_profile': 'Developer & Community',
    'visit_steam': 'Visit Pinyo\'s Profile',
    'bug_report': 'Bug Report & Feedback',
    'bug_report_note': 'Please report data errors or app bugs via Steam message.',
    'copy_link': 'Copy Link',
    'link_copied': 'Link copied to clipboard!',
    'long_press_copy': 'Long press to copy',
    'tomorrow': 'Tomorrow',
    'standard_dd': 'STANDARD DEEP DIVE',
    'elite_dd': 'ELITE DEEP DIVE',
    'Azure Weald': 'Azure Weald',
    'Crystalline Caverns': 'Crystalline Caverns',
    'Dense Biozone': 'Dense Biozone',
    'Fungus Bogs': 'Fungus Bogs',
    'Glacial Strata': 'Glacial Strata',
    'Hollow Bough': 'Hollow Bough',
    'Magma Core': 'Magma Core',
    'Radioactive Exclusion Zone': 'Radioactive Exclusion Zone',
    'Salt Pits': 'Salt Pits',
    'Sandblasted Corridors': 'Sandblasted Corridors',
    'Ossuary Depths': 'Ossuary Depths',
    'Mining Expedition': 'Mining Expedition',
    'Egg Hunt': 'Egg Hunt',
    'On-Site Refining': 'On-Site Refining',
    'Point Extraction': 'Point Extraction',
    'Salvage Operation': 'Salvage Operation',
    'Escort Duty': 'Escort Duty',
    'Elimination': 'Elimination',
    'Industrial Sabotage': 'Industrial Sabotage',
    'Deep Scan': 'Deep Scan',
    'Heavy Excavation': 'Heavy Excavation',
    'Double XP': 'Double XP',
    'Gold Rush': 'Gold Rush',
    'Mineral Mania': 'Mineral Mania',
    'Low Gravity': 'Low Gravity',
    'Rich Atmosphere': 'Rich Atmosphere',
    'Critical Weakness': 'Critical Weakness',
    'Golden Bugs': 'Golden Bugs',
    'Volatile Guts': 'Volatile Guts',
    'Shield Disruption': 'Shield Disruption',
    'Mactera Plague': 'Mactera Plague',
    'Cave Leech Cluster': 'Cave Leech Cluster',
    'Parasites': 'Parasites',
    'Exploder Infestation': 'Exploder Infestation',
    'Lethal Enemies': 'Lethal Enemies',
    'Low Oxygen': 'Low Oxygen',
    'Haunted Cave': 'Haunted Cave',
    'Elite Threat': 'Elite Threat',
    'Swarmageddon': 'Swarmageddon',
    'Rival Presence': 'Rival Presence',
    'Lithophage Outbreak': 'Lithophage Outbreak',
    'Regenerative Bugs': 'Regenerative Bugs',
    'Pit Jaw Colony': 'Pit Jaw Colony',
    'Duck and Cover': 'Duck and Cover',
    'Ebonite Outbreak': 'Ebonite Outbreak',
    'Scrab Nesting Grounds': 'Scrab Nesting Grounds',
    'signal_lost': 'SIGNAL LOST!',
    'signal_lost_desc': 'Bosco lost signal! Data is too old.',
    'offline_mode': 'OFFLINE MODE',
    'offline_mode_desc': 'Poor signal from Hoxxes. Using cached data.',
    'dd_loading': 'Loading Deep Dive data...',
    'dd_error': 'Failed to load Deep Dive data.',
    'dd_next_update': 'Next Update:',
    'no_warnings': 'No Warnings',
  },
  'CN': {
    'title': '博斯科终端',
    'live': '实时',
    'highlights': '精彩',
    'deep_dives': '深潜',
    'settings': '设置',
    'lang_select': '系统语言',
    'season_select': '活跃赛季',
    'season_note': '提供来自数据源的所有赛季数据。',
    'standard': '标准 (Standard)',
    'show_warnings': '显示任务提示',
    'donation': '赞助开发人员',
    'donate_note': '捐赠将用于 Store 费用和维护。',
    'disclaimer_title': '免责声明与权利声明',
    'disclaimer_body': '本程序是与 Ghost Ship Games 无关的非官方粉丝项目。DRG 的所有资产和商标均归原作者所有。实时数据来自 doublexp.net。特别感谢 rolfosian (GitHub) 分析了游戏内的任务生成逻辑，并提供了这一重构的数据源。',
    'current': '当前',
    'upcoming': '下一次任务',
    'past': '已结束',
    'length': '长度',
    'complexity': '复杂度',
    'time_left': '下一次轮환:',
    'timeline_title': '今日主要任务时间线',
    'now': '--- [ 当前时间 ] ---',
    'details': '任务详情',
    'close': '关闭',
    'no_highlights': '今日未发现特殊任务。',
    'steam_profile': '开发人员与社区',
    'visit_steam': '访问 Pinyo 的个人资料',
    'bug_report': '错误报告和反馈',
    'bug_report_note': '请通过 Steam 消息报告数据错误 or 程序错误。',
    'copy_link': '复制链接',
    'link_copied': '链接已复制到剪贴板！',
    'long_press_copy': '长按复制链接',
    'tomorrow': '明天',
    'standard_dd': '普通深潜',
    'elite_dd': '精英深潜',
    'Azure Weald': '蔚蓝旷野',
    'Crystalline Caverns': '水晶洞窟',
    'Dense Biozone': '稠密生物区',
    'Fungus Bogs': '菌类蔓延',
    'Glacial Strata': '冰川地层',
    'Hollow Bough': '空洞树干',
    'Magma Core': '熔岩核心',
    'Radioactive Exclusion Zone': '放射性排斥区',
    'Salt Pits': '盐坑',
    'Sandblasted Corridors': '喷砂走廊',
    'Ossuary Depths': '纳骨堂深处',
    'Mining Expedition': '采矿远征',
    'Egg Hunt': '搜寻异形蛋',
    'On-Site Refining': '就地精련',
    'Point Extraction': '定点提取',
    'Salvage Operation': '打捞行动',
    'Escort Duty': '护送任务',
    'Elimination': '消灭',
    'Industrial Sabotage': '工业破坏',
    'Deep Scan': '深层扫描',
    'Heavy Excavation': '重型挖掘',
    'Double XP': '双倍经验',
    'Gold Rush': '淘金热',
    'Mineral Mania': '矿물狂热',
    'Low Gravity': '低重力',
    'Rich Atmosphere': '富氧环境',
    'Critical Weakness': '致命弱点',
    'Golden Bugs': '黄金虫',
    'Volatile Guts': '易爆内脏',
    'Shield Disruption': '护盾破坏',
    'Mactera Plague': '摩克特拉瘟疫',
    'Cave Leech Cluster': '洞穴水蛭集群',
    'Parasites': '寄生虫',
    'Exploder Infestation': '自爆感染',
    'Lethal Enemies': '致命敌人',
    'Low Oxygen': '缺氧环境',
    'Haunted Cave': '闹鬼洞穴',
    'Elite Threat': '精英威胁',
    'Swarmageddon': '异形虫灾',
    'Rival Presence': '对手存在',
    'Lithophage Outbreak': '岩噬爆发',
    'Regenerative Bugs': '再生虫',
    'Pit Jaw Colony': '坑口鳄群落',
    'Duck and Cover': '卧倒！',
    'Ebonite Outbreak': '乌木爆发',
    'Scrab Nesting Grounds': '虫巢地带',
    'signal_lost': '信号丢失！',
    'signal_lost_desc': 'Bosco失去信号！数据已过时。',
    'offline_mode': '离线模式',
    'offline_mode_desc': 'Hoxxes信号不佳。正在使用缓存数据。',
    'dd_loading': '正在加载深潜数据...',
    'dd_error': '无法加载深潜数据。',
    'dd_next_update': '下次更新:',
    'no_warnings': '无警告',
  }
};

String t(String? key, String lang) {
  if (key == null || key.isEmpty) return "";
  return i18n[lang]?[key] ?? key;
}
