const Map<String, Map<String, String>> i18n = {
  'KR': {
    'title': 'BOSCO TERMINAL',
    'live': 'Live',
    'highlights': 'DoubleXP',
    'deep_dives': 'Deep Dive',
    'settings': '설정',
    'lang_select': '시스템 언어 선택',
    'season_select': '활성 시즌 선택',
    'season_note': '데이터 소스에서 제공하는 모든 시즌 정보를 제공합니다.',
    'standard': '표준 (Standard)',
    'show_warnings': '미션 주의사항 표시',
    'donation': '개발자 후원',
    'donate_note': '후원금은 Apple Store 등록비 및 서버 유지비로 사용됩니다.',
    'disclaimer_title': '면책 조항 및 권리 고지',
    'disclaimer_body': '본 앱은 Ghost Ship Games와 관련이 없는 비공식 팬 프로젝트입니다. DRG의 모든 자산 및 상표권은 원작자에게 있습니다. 실시간 데이터는 doublexp.net에서 제공되며, 게임 내 미션 생성 로직을 분석하여 정제된 데이터를 공유해주신 rolfosian(GitHub)님께 특별한 감사를 표합니다.',
    'current': '현재 진행 중',
    'upcoming': '다음 미션',
    'past': '종료된 미션',
    'length': '길이',
    'complexity': '복잡도',
    'time_left': '다음 로테이션:',
    'timeline_title': '오늘의 주요 미션 타임라인',
    'now': '--- [ 현재 시간 ] ---',
    'details': '미션 상세 정보',
    'close': '닫기',
    'no_highlights': '오늘의 특별한 미션이 없습니다.',
    'steam_profile': 'Developer & Community',
    'visit_steam': 'Pinyo의 프로필 방문',
    'bug_report': '버그 제보 및 수정 문의',
    'bug_report_note': '미션 데이터 오류나 앱 버그는 스팀 메시지로 알려주세요.',
    'copy_link': '링크 복사',
    'link_copied': '클립보드에 복사되었습니다!',
    'long_press_copy': '길게 누르면 링크 복사',
    'tomorrow': '내일 일정',
    
    'standard_dd': '일반 딥 다이브',
    'elite_dd': '엘리트 딥 다이브',

    // Map Name
    'Azure Weald': '바닷빛 삼림',
    'Crystalline Caverns': '크리스탈라인 동굴',
    'Dense Biozone': '고밀도 생태지역',
    'Fungus Bogs': '곰팡이 늪지',
    'Glacial Strata': '빙하 지층',
    'Hollow Bough': '공허한 가지',
    'Magma Core': '마그마의 중심',
    'Radioactive Exclusion Zone': '방사능 위험 지역',
    'Salt Pits': '소금 구덩이',
    'Sandblasted Corridors': '사막화 지대',
    'Ossuary Depths': '뼈동굴 심층부',

    // Mission Type
    'Mining Expedition': '채굴 원정',
    'Egg Hunt': '알 추적',
    'On-Site Refining': '현장 정제',
    'Point Extraction': '채굴 지점',
    'Salvage Operation': '구조 임무',
    'Escort Duty': '호위 임무',
    'Elimination': '섬멸',
    'Industrial Sabotage': '기업 방해공작',
    'Deep Scan': '심층 탐사',
    'Heavy Excavation': '대형 발굴',

    // 미션 관련 텍스트
    'secondary_obj': '보조 목표',
    'Fossils': '화석',
    'Glyphid Eggs': '글리피드 알',
    'Boolo Caps': '블루 버섯',
    'Compressed Gold': '압축 금',
    'Dystrum': '디스트럼',
    'Ebonuts': '에보넛',
    'Apoca Blooms': '아포카 꽃',
    'Gunk Seeds': '겅크 시드',
    'Hollomite': '홀로마이트',
    'Jadiz': '자디즈',
    'Lost Pack': '잃어버린 장비',
    'Morkite': '모르카이트',
    'Phazyonite': '파지오나이트',
    'Red Sugar': '레드 슈거',
    'Fester Fleas': '패스터플리',
    'Bha Barnacles': '바하 바나클',
    
    // Mutators & Warnings
    'Double XP': '경험치 2배',
    'Gold Rush': '골드 러쉬',
    'Mineral Mania': '광물 마니아',
    'Low Gravity': '저중력',
    'Rich Atmosphere': '풍부한 산소',
    'Critical Weakness': '치명적 약점',
    'Golden Bugs': '황금 벌레',
    'Volatile Guts': '불안정한 내장',
    'Blood Sugar': '혈당',
    'Secret Secondary': '비밀 보조 목표',
    'ApocaBlooms': '아포카 꽃', // 데이터 키가 CamelCase로 올 때 대응
    'Shield Disruption': '보호막 없음',
    'Mactera Plague': '막테라 역병',
    'Cave Leech Cluster': '케이브 리치 군집',
    'Parasites': '기생충',
    'Exploder Infestation': '익스플로더 침공',
    'Lethal Enemies': '치명적인 적',
    'Low Oxygen': '저산소',
    'Haunted Cave': '유령 동굴',
    'Elite Threat': '엘리트 위협',
    'Swarmageddon': '폭풍공세',
    'Rival Presence': '경쟁기업 주둔지',
    'Lithophage Outbreak': '리쏘파지 발생',
    'Regenerative Bugs': '재생하는 벌레',
    'Pit Jaw Colony': '핏죠 군락',
    'Duck and Cover': '탄막 지옥',
    'Ebonite Outbreak': '에보나이트 발생',
    'Scrab Nesting Grounds': '스크랩 둥지',

    // System
    'signal_lost': '통신 두절!',
    'signal_lost_desc': '보스코가 신호를 잃었습니다! 데이터가 너무 오래되었습니다.',
    'offline_mode': '오프라인 모드',
    'offline_mode_desc': 'Hoxxes 전파 상태가 좋지 않습니다. 캐시된 데이터를 사용 중입니다.',
    'dd_loading': '딥 다이브 데이터를 불러오는 중...',
    'dd_error': '딥 다이브 데이터를 불러올 수 없습니다.',
    'dd_next_update': '다음 갱신:',
    'no_warnings': '주의사항 없음',

    // Trivia
    'trivia_tips': '팁',
    'trivia_close': '닫기',
    'trivia_no_info': '정보가 준비되지 않았습니다.',
    // Notification
    'notif_settings': 'Double XP 알림',
    'notif_enable': '알림 활성화',
    'notif_double_xp_desc': 'Double XP 버프가 있는 미션에만 알림을 전송합니다.',
    'notif_platform_unsupported': 'Push 알림은 Android에서만 지원됩니다.',
    'notif_time_from': '시작',
    'notif_time_to': '종료',
    'notif_time': '알림 시간',
    'notif_days': '활성 요일',
    'notif_exclude_types': '미션 타입 필터',
    'notif_exclude_note': '해제된 타입은 Double XP여도 알림을 보내지 않습니다.',
    'notif_title': '보스코 터미널',
    'notif_body_prefix': 'Double XP 미션 발견!',
    'notif_summary': '{n}개 Double XP 미션',
    'notif_permission_required': '알림 권한이 필요합니다.',
    'notif_permission_denied': '설정에서 알림 권한을 허용해주세요.',
    'mon': '월', 'tue': '화', 'wed': '수', 'thu': '목',
    'fri': '금', 'sat': '토', 'sun': '일',
    // Update Dialog
    'update_available': '새 버전이 있습니다',
    'update_required': '필수 업데이트',
    'update_now': '지금 업데이트',
    'update_later': '나중에',
    'update_changelog': '변경 사항',
    'update_ver_current': '현재 버전',
    'update_ver_new': '새 버전',
    'update_force_desc': '앱을 계속 사용하려면 업데이트가 필요합니다.',
  },
  'EN': {
    'title': 'BOSCO TERMINAL',
    'live': 'LIVE',
    'highlights': 'HIGHLIGHTS',
    'deep_dives': 'DEEP DIVES',
    'settings': 'SETTINGS',
    'lang_select': 'System Language',
    'season_select': 'Active Season',
    'season_note': 'Providing all season data from the source.',
    'standard': 'Standard',
    'show_warnings': 'Show Mission Warnings',
    'donation': 'Support Developer',
    'donate_note': 'Used for Store fees and maintenance.',
    'disclaimer_title': 'Legal Disclaimer',
    'disclaimer_body': 'This app is an unofficial fan project and is not affiliated with Ghost Ship Games. All game assets and trademarks belong to their respective owners. Real-time data is sourced from doublexp.net. Special thanks to rolfosian (GitHub) for analyzing the in-game mission generation logic and providing this reconstructed data source.',
    'current': 'CURRENT',
    'upcoming': 'UPCOMING',
    'past': 'PAST',
    'length': 'Length',
    'complexity': 'Complexity',
    'time_left': 'Next Rotation:',
    'timeline_title': 'Today\'s Highlight Timeline',
    'now': '--- [ CURRENT TIME ] ---',
    'details': 'Mission Details',
    'close': 'CLOSE',
    'no_highlights': 'No special missions found for today.',
    'steam_profile': 'Developer & Community',
    'visit_steam': 'Visit Pinyo\'s Profile',
    'bug_report': 'Bug Report & Feedback',
    'bug_report_note': 'Please report data errors or app bugs via Steam message.',
    'copy_link': 'Copy Link',
    'link_copied': 'Link copied to clipboard!',
    'long_press_copy': 'Long press to copy',
    'tomorrow': 'Tomorrow',
    'standard_dd': 'STANDARD DEEP DIVE',
    'elite_dd': 'ELITE DEEP DIVE',
    'Azure Weald': 'Azure Weald',
    'Crystalline Caverns': 'Crystalline Caverns',
    'Dense Biozone': 'Dense Biozone',
    'Fungus Bogs': 'Fungus Bogs',
    'Glacial Strata': 'Glacial Strata',
    'Hollow Bough': 'Hollow Bough',
    'Magma Core': 'Magma Core',
    'Radioactive Exclusion Zone': 'Radioactive Exclusion Zone',
    'Salt Pits': 'Salt Pits',
    'Sandblasted Corridors': 'Sandblasted Corridors',
    'Ossuary Depths': 'Ossuary Depths',
    'Mining Expedition': 'Mining Expedition',
    'Egg Hunt': 'Egg Hunt',
    'On-Site Refining': 'On-Site Refining',
    'Point Extraction': 'Point Extraction',
    'Salvage Operation': 'Salvage Operation',
    'Escort Duty': 'Escort Duty',
    'Elimination': 'Elimination',
    'Industrial Sabotage': 'Industrial Sabotage',
    'Deep Scan': 'Deep Scan',
    'Heavy Excavation': 'Heavy Excavation',

    // Secondary Objective
    'secondary_obj': 'Secondary',
    'Fossils': 'Fossils',
    'Glyphid Eggs': 'Glyphid Eggs',
    'Boolo Caps': 'Boolo Caps',
    'Compressed Gold': 'Compressed Gold',
    'Dystrum': 'Dystrum',
    'Ebonuts': 'Ebonuts',
    'Apoca Blooms': 'Apoca Blooms',
    'Gunk Seeds': 'Gunk Seeds',
    'Hollomite': 'Hollomite',
    'Jadiz': 'Jadiz',
    'Lost Pack': 'Lost Pack',
    'Morkite': 'Morkite',
    'Phazyonite': 'Phazyonite',
    'Red Sugar': 'Red Sugar',
    'Fester Fleas': 'Fester Fleas',
    'Bha Barnacles': 'Bha Barnacles',

    'Double XP': 'Double XP',
    'Gold Rush': 'Gold Rush',
    'Mineral Mania': 'Mineral Mania',
    'Low Gravity': 'Low Gravity',
    'Rich Atmosphere': 'Rich Atmosphere',
    'Critical Weakness': 'Critical Weakness',
    'Golden Bugs': 'Golden Bugs',
    'Volatile Guts': 'Volatile Guts',
    'Blood Sugar': 'Blood Sugar',
    'Secret Secondary': 'Secret Secondary',
    'ApocaBlooms': 'Apoca Blooms', // CamelCase alias
    'Shield Disruption': 'Shield Disruption',
    'Mactera Plague': 'Mactera Plague',
    'Cave Leech Cluster': 'Cave Leech Cluster',
    'Parasites': 'Parasites',
    'Exploder Infestation': 'Exploder Infestation',
    'Lethal Enemies': 'Lethal Enemies',
    'Low Oxygen': 'Low Oxygen',
    'Haunted Cave': 'Haunted Cave',
    'Elite Threat': 'Elite Threat',
    'Swarmageddon': 'Swarmageddon',
    'Rival Presence': 'Rival Presence',
    'Lithophage Outbreak': 'Lithophage Outbreak',
    'Regenerative Bugs': 'Regenerative Bugs',
    'Pit Jaw Colony': 'Pit Jaw Colony',
    'Duck and Cover': 'Duck and Cover',
    'Ebonite Outbreak': 'Ebonite Outbreak',
    'Scrab Nesting Grounds': 'Scrab Nesting Grounds',
    'signal_lost': 'SIGNAL LOST!',
    'signal_lost_desc': 'Bosco lost signal! Data is too old.',
    'offline_mode': 'OFFLINE MODE',
    'offline_mode_desc': 'Poor signal from Hoxxes. Using cached data.',
    'dd_loading': 'Loading Deep Dive data...',
    'dd_error': 'Failed to load Deep Dive data.',
    'dd_next_update': 'Next Update:',
    'no_warnings': 'No Warnings',
    // Trivia
    'trivia_tips': 'Tips',
    'trivia_close': 'CLOSE',
    'trivia_no_info': 'No information available.',
    // Notification
    'notif_settings': 'Double XP Alerts',
    'notif_enable': 'Enable Alerts',
    'notif_double_xp_desc': 'Alerts are only sent for missions with Double XP buff.',
    'notif_platform_unsupported': 'Push alerts are only supported on Android.',
    'notif_time_from': 'From',
    'notif_time_to': 'To',
    'notif_time': 'Alert Time',
    'notif_days': 'Active Days',
    'notif_exclude_types': 'Mission Type Filter',
    'notif_exclude_note': 'Excluded types will be skipped even on Double XP.',
    'notif_title': 'Bosco Terminal',
    'notif_body_prefix': 'Double XP mission available!',
    'notif_summary': '{n} Double XP missions',
    'notif_permission_required': 'Notification permission required.',
    'notif_permission_denied': 'Please allow notification permission in Settings.',
    'mon': 'Mon', 'tue': 'Tue', 'wed': 'Wed', 'thu': 'Thu',
    'fri': 'Fri', 'sat': 'Sat', 'sun': 'Sun',
    // Update Dialog
    'update_available': 'Update Available',
    'update_required': 'Update Required',
    'update_now': 'Update Now',
    'update_later': 'Later',
    'update_changelog': "What's New",
    'update_ver_current': 'Current',
    'update_ver_new': 'New',
    'update_force_desc': 'An update is required to continue using the app.',
  },
  'CN': {
    'title': '博斯科终端',
    'live': '实时',
    'highlights': '精彩',
    'deep_dives': '深潜',
    'settings': '设置',
    'lang_select': '系统语言',
    'season_select': '活跃赛季',
    'season_note': '提供来自数据源的所有赛季数据。',
    'standard': '标准 (Standard)',
    'show_warnings': '显示任务提示',
    'donation': '赞助开发人员',
    'donate_note': '捐赠将用于 Store 费用和维护。',
    'disclaimer_title': '免责声明与权利声明',
    'disclaimer_body': '本程序是与 Ghost Ship Games 无关的非官方粉丝项目。DRG 的所有资产和商标均归原作者所有。实时数据来自 doublexp.net。特别感谢 rolfosian (GitHub) 分析了游戏内的任务生成逻辑，并提供了这一重构的数据源。',
    'current': '当前',
    'upcoming': '下一次任务',
    'past': '已结束',
    'length': '长度',
    'complexity': '复杂度',
    'time_left': '下一次轮환:',
    'timeline_title': '今日主要任务时间线',
    'now': '--- [ 当前时间 ] ---',
    'details': '任务详情',
    'close': '关闭',
    'no_highlights': '今日未发现特殊任务。',
    'steam_profile': '开发人员与社区',
    'visit_steam': '访问 Pinyo 的个人资料',
    'bug_report': '错误报告和反馈',
    'bug_report_note': '请通过 Steam 消息报告数据错误 or 程序错误。',
    'copy_link': '复制链接',
    'link_copied': '链接已复制到剪贴板！',
    'long_press_copy': '长按复制链接',
    'tomorrow': '明天',
    'standard_dd': '普通深潜',
    'elite_dd': '精英深潜',
    'Azure Weald': '蔚蓝旷野',
    'Crystalline Caverns': '水晶洞窟',
    'Dense Biozone': '稠密生物区',
    'Fungus Bogs': '菌类蔓延',
    'Glacial Strata': '冰川地层',
    'Hollow Bough': '空洞树干',
    'Magma Core': '熔岩核心',
    'Radioactive Exclusion Zone': '放射性排斥区',
    'Salt Pits': '盐坑',
    'Sandblasted Corridors': '喷砂走廊',
    'Ossuary Depths': '纳骨堂深处',
    'Mining Expedition': '采矿远征',
    'Egg Hunt': '搜寻异形蛋',
    'On-Site Refining': '就地精련',
    'Point Extraction': '定点提取',
    'Salvage Operation': '打捞行动',
    'Escort Duty': '护送任务',
    'Elimination': '消灭',
    'Industrial Sabotage': '工业破坏',
    'Deep Scan': '深层扫描',
    'Heavy Excavation': '重型挖掘',

    // Secondary Objective
    'secondary_obj': '次要目标',
    'Fossils': '化石',
    'Glyphid Eggs': '格里菲德蛋',
    'Boolo Caps': '布洛菌帽',
    'Compressed Gold': '压缩黄金',
    'Dystrum': '代斯特拉姆',
    'Ebonuts': '乌木果',
    'Apoca Blooms': '末日花',
    'Gunk Seeds': '黏液种子',
    'Hollomite': '空洞石',
    'Jadiz': '翡翠石',
    'Lost Pack': '失落装备',
    'Morkite': '墨石',
    'Phazyonite': '法兹石',
    'Red Sugar': '红糖',
    'Fester Fleas': '腐烂跳蚤',
    'Bha Barnacles': 'Bha藤壶',

    'Double XP': '双倍经验',
    'Gold Rush': '淘金热',
    'Mineral Mania': '矿물狂热',
    'Low Gravity': '低重力',
    'Rich Atmosphere': '富氧环境',
    'Critical Weakness': '致命弱点',
    'Golden Bugs': '黄金虫',
    'Volatile Guts': '易爆内脏',
    'Blood Sugar': '血糖',
    'Secret Secondary': '秘密次要目标',
    'ApocaBlooms': '末日花', // CamelCase alias
    'Shield Disruption': '护盾破坏',
    'Mactera Plague': '摩克特拉瘟疫',
    'Cave Leech Cluster': '洞穴水蛭集群',
    'Parasites': '寄生虫',
    'Exploder Infestation': '自爆感染',
    'Lethal Enemies': '致命敌人',
    'Low Oxygen': '缺氧环境',
    'Haunted Cave': '闹鬼洞穴',
    'Elite Threat': '精英威胁',
    'Swarmageddon': '异形虫灾',
    'Rival Presence': '对手存在',
    'Lithophage Outbreak': '岩噬爆发',
    'Regenerative Bugs': '再生虫',
    'Pit Jaw Colony': '坑口鳄群落',
    'Duck and Cover': '卧倒！',
    'Ebonite Outbreak': '乌木爆发',
    'Scrab Nesting Grounds': '虫巢地带',
    'signal_lost': '信号丢失！',
    'signal_lost_desc': 'Bosco失去信号！数据已过时。',
    'offline_mode': '离线模式',
    'offline_mode_desc': 'Hoxxes信号不佳。正在使用缓存数据。',
    'dd_loading': '正在加载深潜数据...',
    'dd_error': '无法加载深潜数据。',
    'dd_next_update': '下次更新:',
    'no_warnings': '无警告',
    // Trivia
    'trivia_tips': '提示',
    'trivia_close': '关闭',
    'trivia_no_info': '暂无相关信息。',
    // Notification
    'notif_settings': '双倍经验提醒',
    'notif_enable': '启用提醒',
    'notif_double_xp_desc': '仅在任务有双倍经验增益时发送提醒。',
    'notif_platform_unsupported': 'Push提醒仅支持Android平台。',
    'notif_time_from': '开始',
    'notif_time_to': '结束',
    'notif_time': '提醒时间',
    'notif_days': '活跃日',
    'notif_exclude_types': '任务类型过滤',
    'notif_exclude_note': '已排除的类型即使有双倍经验也不发送提醒。',
    'notif_title': '博斯科终端',
    'notif_body_prefix': '发现双倍经验任务！',
    'notif_summary': '{n}个双倍经验任务',
    'notif_permission_required': '需要通知权限。',
    'notif_permission_denied': '请在设置中允许通知权限。',
    'mon': '一', 'tue': '二', 'wed': '三', 'thu': '四',
    'fri': '五', 'sat': '六', 'sun': '日',
    // Update Dialog
    'update_available': '有新版本',
    'update_required': '需要更新',
    'update_now': '立即更新',
    'update_later': '稍后',
    'update_changelog': '更新内容',
    'update_ver_current': '当前版本',
    'update_ver_new': '新版本',
    'update_force_desc': '需要更新才能继续使用应用。',
  }
};

// ── 동적 오버라이드 맵 ──────────────────────────────────────────────────────────
// StringsService가 GitHub data/strings.json을 fetch하면 이 맵을 채움.
// t()가 이 맵을 먼저 확인하므로, 앱 업데이트 없이 번역 수정 가능.
Map<String, Map<String, String>> dynamicOverlay = {};

String t(String? key, String lang) {
  if (key == null || key.isEmpty) return "";
  // 동적 오버라이드 먼저 확인 → 정적 i18n → 원본 키 fallback
  return dynamicOverlay[lang]?[key] ?? i18n[lang]?[key] ?? key;
}
